name: DevOps Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: build da aplicacao
        run: echo "buildando a aplicacao!"
    
  dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: fase de desenvolvimento
        run: echo "Deploy no ambiente de desenvolvimento!"

  qa:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: fase de testes
        run: echo "teste de qualidade"
    
  homologacao:
    needs:
    - dev
    - qa
    runs-on: ubuntu-latest

    steps:
      - name: Ambiente de homologacao
        run: echo "Executando deploy no ambiente de homologacao"  

  producao:
    needs: homologacao
    runs-on: ubuntu-latest

    steps:
      - name: deploy producao
        run: echo "execultando deploy em prod"    


