name: DevOps Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: Mostrar mensagem
        run: echo "Olá, mundo DevOps!"


